[env]
_.python.venv = { path = ".venv", create = true }

[tasks.format]
run = [
  'black leetcode/**/*.py',
  'black daily-interview-pro/**/*.py',
]

[tasks.setup]
run = [
  'pip install -r requirements.txt',
]
